### PR TITLE
Student Groups / Projects

### PR DESCRIPTION
**Pull request by digikami**
Adds class/student group/project functionality.

### CODE REVIEW

**Comment by digikami** [comment]
[Dashboard - Lab Management](https://trello.com/c/FFlY5a3K/8-dashboard-lab-management)

**Comment by digikami** [comment]
[Dashboard - Class Management](https://trello.com/c/v4qNYPF5/9-dashboard-class-management)

**Comment by enginbumbacher** [comment]
Somehow this didn't work for me. I created a project (Btw, the home page for teachers says "Manage Classes"), and added student1 as a valid student ID. But when I want to log in as student1, I get a "login failed" error. When I login as student2, I get "invalid login", as to be expected. Same problem with student1@jls.edu or so. (I wasn't sure whether email format is still required, or whether we opened it up now.) Also, because of that I couldn't verify how the user gets stored in the database.

**Comment by enginbumbacher** [comment]
I saw the error message now, and figured out what the problem was. Unhandled error for request POST /api/v1/Students/login: Error: This lab is not assigned to this Project
    at Promise.all.then (/Users/Engin/Dropbox/Akademia/Projects/BioLab/LabInTheCloud/common/models/student.js:35:17)

I think it would be helpful if the error message for this case was not "login failed" but "lab not assigned to project". I assume this error will only occur on the teacher / admin side.

**Comment by digikami** [comment]
@enginbumbacher I've added the fix we discussed: labs not assigned to a student group won't be publicly accessible anymore, so that error _shouldn't_ be relevant anymore.

**Comment by enginbumbacher** [comment]
Cool. Works now. Thanks!

**Pull request merged**
