### PR TITLE
Lab Administration

### PR DESCRIPTION
**Pull request by digikami**
Adds basic lab creation and management

### CODE REVIEW

**Comment by enginbumbacher** [comment]
I ran into the following problem: I create a user, and then I want to create a lab. This is the error message I get:
screen shot 2018-10-04 at 10 11 23 am
screen shot 2018-10-04 at 10 11 32 am

**Comment by enginbumbacher** [comment]
Ah, I forgot that the URL field has to be manually populated. I assumed it'd be automated, somehow... Another question: I created multiple teachers; for some teachers, the random generated identifier after lab/ does not appear, so the url is .../lab// . For others it does. 

I assume in the next iteration, the random identifier will be replaced by the teacher/class structure?

**Comment by enginbumbacher** [comment]
New error. When I create a lab, go back to "Manage Labs", and then want to access the dashboard again for the lab I created, I see a blank page, and get the following error:
screen shot 2018-10-04 at 10 37 19 am

**Comment by enginbumbacher** [comment]
So far, I found three issues: 
1.  It is hard to test the system entirely without the experiment servers working. I chose demo for the experiment, but it does not load. How did you configure the demo?
2. The system allows a user to create two labs that happen to have exactly the same URL.
3. As an admin, I can't see the labs created by the users (unless this feature has not been built yet).

**Comment by digikami** [comment]
(1) I agree. These changes should be removing the need for a demo mode, but I can look into this if you like.
(2) I have added a solution for this in the sandbox branch.
(3) The functionality exists, but it is not currently exposed. Administrators can see individual users' labs by using the path /admin/user/:userId/labs. I will be adding a link to the user listing in a later pull request.

**Comment by enginbumbacher** [comment]
Great, experiments, etc. have been cleaned up, so demo mode works now. 

Current problems when wanting to create a new sublab:
1. If I want to have a blockly model that has parameters (e.g. opacity, K, V) not available to students, with a set value, I can't change the value it should be set to. The fields seem disabled.
2. See screenshot 1: There is a weird error: I want to subselect blocks available to students. I select all blocks except for "turn change", the "Forward" tab in blockly disappears; if I select all blocks except for "rotation change", the "Additional Blocks" tab in blockly disappears. It seems to be always the tab after the disabled block. Not if I disable any other block.
3. See screenshot 2: When I want to add another option for Euglena Initialization in Modeling: I click on the last line, and then press "return" on my keyboard, suddenly 10 fields of "Lab Saved" appear, and I can't change anything.

Screenshot 1:
screen shot 2018-10-13 at 8 02 10 pm



Screenshot 2:
screen shot 2018-10-13 at 7 55 41 pm

**Comment by digikami** [comment]
I've just pushed a correction for issues (1) and (3) from your last comment. I am seeing issue (2), but it seems to be gone in the admin_filter branch. Could you check and confirm?

**Comment by enginbumbacher** [comment]
(2) does not seem solved on the admin_filter branch either. In fact, I realized there is a new problem: 
1. I disable a block, e.g. 'turn change'.
2. I click on "Submit".
3. I click on "Preview Student".
4. The supposedly disabled block still appears under the "turn" tab.
5. I close the preview student.
6. I do something else (anything), and then open preview student again.
7. The supposedly disabled block still appears. But on top of that, each block in each tab is replicated again. So, when I repeat step 5 and 6, I will see each block replicated in each blockly tab for the number of times I repeated the steps. 

But when I go onto the actual website, the number of blocks in each tab is unchanged, i.e. neither are blocks repeated nor are disabled blocks disabled.

Here is the series of screenshots of the "turn" tab after the first repeat:
screen shot 2018-10-15 at 11 54 31 am
screen shot 2018-10-15 at 11 54 44 am
screen shot 2018-10-15 at 11 54 49 am

**Comment by enginbumbacher** [comment]
(1) works now in terms of being able to change values. When I fix values for Omega or K, things work fine in terms of the value represented, and the corresponding Euglena model image generated. But when I fix V, the Euglena model image is not generated correctly. See screenshot. A purple arrow, and the purple square at the base of the flagellum should appear.

screen shot 2018-10-15 at 12 07 55 pm

**Comment by enginbumbacher** [comment]
(3) works for me now.

**Comment by enginbumbacher** [comment]
These three last comments all come from reviewing the admin_filter branch; I assume that it's the same on the original admin branch.

**Pull request merged**
