### PR TITLE
Adds support for teachers to name experiment presets

### PR DESCRIPTION
**Pull request by digikami**

### CODE REVIEW

**Comment by digikami** [comment]
[Support for Experiment naming](https://trello.com/c/4knJ8HoE/12-support-for-experiment-naming)

**Comment by enginbumbacher** [comment]
Love the implementation. Works beautifully as the teacher. I'm wondering even whether we should / could include that for the students?

**Comment by digikami** [comment]
I set it up as a configurable option, so you could include it for students pretty easily, you'd just need to add that field into the lab configuration form (experiment.allowNames, true/false). Whether you should or not is up to you. I think requiring a name, especially in the context of a new user creating their first experiment, would be an unnecessary speed bump on the learning curve, but I can see the utility for a more advanced user.

**Comment by enginbumbacher** [comment]
Great! Yes, I fully agree, it's better for people who have some familiarity
with the system and need to generate more of their own results.

**Pull request merged**
